@PricingMicroService_HostAddress = http://localhost:7275

### Calls Service A to calculate the price of serviceA as customer(0) between the dates of 2019-05-23 and 2020-01-01 {"CustomerId":0,"StartDate":"2019-05-23","EndDate":"2020-01-01"}
GET {{PricingMicroService_HostAddress}}/Pricing/servicea?request=%7B%22CustomerId%22%3A0%2C%22StartDate%22%3A%222019-05-23%22%2C%22EndDate%22%3A%222020-01-01%22%7D
Accept: application/json

###

### Calls Service B to calculate the price of serviceB as customer(0) between the dates of 2019-05-23 and 2020-01-01 {"CustomerId":0,"StartDate":"2019-05-23","EndDate":"2020-01-01"}
GET {{PricingMicroService_HostAddress}}/Pricing/serviceb?request=%7B%22CustomerId%22%3A0%2C%22StartDate%22%3A%222019-05-23%22%2C%22EndDate%22%3A%222020-01-01%22%7D
Accept: application/json

###

### Calls Service C to calculate the price of serviceC as customer(0) between the dates of 2019-05-23 and 2020-01-01 {"CustomerId":0,"StartDate":"2019-05-23","EndDate":"2020-01-01"}
GET {{PricingMicroService_HostAddress}}/Pricing/servicec?request=%7B%22CustomerId%22%3A0%2C%22StartDate%22%3A%222019-05-23%22%2C%22EndDate%22%3A%222020-01-01%22%7D
Accept: application/json

###